version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: django_app_docker_test_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    container_name: migration
    build:
      context: .
      dockerfile: DockerfileLocal
    command: python manage.py migrate
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy

  django_app:
    container_name: django_app_docker_test_dev_app
    build:
      context: .
      dockerfile: DockerfileLocal
    volumes:
      - ./src:/app
      - static:/static
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - app-network

volumes:
  static:
  postgres_data:
    driver: local

networks:
  app-network:
    driver: bridge
